name: "Tests"

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: "
    Python ${{ matrix.python-version }}
    "
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [
          '3.9',
          '3.13',
        ]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      UV_SYSTEM_PYTHON: true

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Install `sponge`
        run: sudo apt-get --yes install moreutils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: |
            pyproject.toml
          cache-suffix: ${{ matrix.python-version }}
          enable-cache: true
          version: "latest"

      - name: Set up project
        run: |
          uv pip install --editable='.[develop,test]'

      - name: Run linter and software tests
        run: |
          poe check
          poe build
          cratedb-about list-questions
